# ~/.config/starship.toml

# Use custom format
format = '''
[┌──\([ ඞ suskellඞ ](sukell)\)─\[[$directory](suskell)\]](pinekell)
[└─](pinekell)[λ](sukell) '''

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

# Define new suspicous colors
pinekell = '#8f4e8b'
sukell = '#5e5086'
suskell = '#453a62'
